site_name: '@iosonogio'
site_description: my digital garden
copyright: Copyright &copy; iosonogio

use_directory_urls: false

nav:
  - Linux: linux
  - Security: security

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey

  features:
    - navigation.indexes
    - navigation.sections

extra:
  generator: false

plugins:

  - search
  - awesome-pages
  - ezlinks
  - tags:
      tags_file: tags.md
  - categories:
      generate_index: true
      verbose: false
      base_name: 'categories'
      section_title: 'Categories'
      no_nav: true
  # - file-filter:
  #     filter_nav: false
  #     metadata_property: visibility
  #     exclude_tag:
  #       - private

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: false
      linenums: true
      anchor_linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
