name: Publish to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: find docs/ -name "*.md" | xargs grep -railF "visibility: private" | xargs rm
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.1'
          cache: 'pip'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run: mkdocs gh-deploy --force

